package org.libreoffice.zoho.ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.libreoffice.zoho.config.Configuration;
import org.libreoffice.zoho.config.Logger;
import org.libreoffice.zoho.handler.Document;
import org.libreoffice.zoho.handler.DocumentFactory;
import org.libreoffice.zoho.handler.LocalStorage;
import org.libreoffice.zoho.handler.Uploader;

/**
 *
 * @author amila
 */
public class Exporter extends javax.swing.JFrame {

    /** Creates new form Exporter */
    private Uploader uploader;
    private DocumentFactory docFactory;
    private Document uploadDoc;
    private ImageIcon zohoLogo;

    public Exporter(Uploader model) {

        try {
            UIManager.setLookAndFeel(Configuration.getInstance().getLookAndFeel());
        } catch (Exception e) {
        }
        this.uploader = model;
        initComponents();
        setGraphics();
        initUI();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileNameField = new javax.swing.JTextField();
        addTagsCkeckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        exportBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(zohoLogo);

        jLabel2.setText("File Name ");

        addTagsCkeckBox.setText("Add document tags");
        addTagsCkeckBox.setToolTipText("Check to add dodument tags");
        addTagsCkeckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTagsCkeckBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("(Seperate multiple tags with commas)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        exportBtn.setText("Export");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTagsCkeckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(exportBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addTagsCkeckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelBtn)
                    .addComponent(exportBtn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-410)/2, (screenSize.height-221)/2, 410, 221);
    }// </editor-fold>//GEN-END:initComponents

    private void addTagsCkeckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTagsCkeckBoxActionPerformed
        // TODO add your handling code here:
        if (addTagsCkeckBox.isSelected()) {
            hidePanel(jPanel1, false);
        } else {
            hidePanel(jPanel1, true);
        }
        pack();
    }//GEN-LAST:event_addTagsCkeckBoxActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed

        Progress uploading = new Progress(new JFrame(), false, "Uploading File...");

        uploader.addObserver(uploading);
        uploading.setVisible(true);
        Logger.log("SetVisible Completed");

        Thread downThread = new Thread() {

            @Override
            public void run() {
                Document uploadedDoc = uploader.Upload(uploadDoc);
                LocalStorage.getInstance().setCurrentDoc(uploadedDoc);
                LocalStorage.getInstance().addToList(uploadedDoc);
            }
        };
        downThread.start();

        this.dispose();
    }//GEN-LAST:event_exportBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void hidePanel(JPanel panel, boolean hide) {
        panel.setEnabled(!hide);
        panel.setVisible(!hide);
    }

    private void setGraphics() {
        ImageIcon zohoIcon;
        

        zohoIcon = new ImageIcon(getClass().getResource("/org/libreoffice/zoho/Resources/zoho_logo.png"));
        Image img = zohoIcon.getImage();
        Image newimg = img.getScaledInstance(zohoIcon.getIconWidth() / 2, zohoIcon.getIconHeight() / 2, java.awt.Image.SCALE_SMOOTH);
        zohoLogo = new ImageIcon(newimg);
        this.setIconImage(new ImageIcon(getClass().getResource("/org/libreoffice/zoho/Resources/zoho_icon.png")).getImage());
    }

     private void initUI() {
        hidePanel(jPanel1, true);
        pack();
        exportBtn.requestFocus();
        docFactory = new DocumentFactory();
        uploadDoc = docFactory.createUploadDoc(uploader.getOpenedDocumentPath());
        fileNameField.setText(uploadDoc.getName());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addTagsCkeckBox;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
