package org.libreoffice.zoho.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Observer;
import java.util.Observable;
import javax.swing.UIManager;
import org.libreoffice.zoho.config.Configuration;

/**
 * @author Amila Surendra
 */
public class Progress extends javax.swing.JDialog implements Observer {

    /** Creates new form Progress */
    public Progress(java.awt.Frame parent, boolean modal, String title) {
        super(parent);
        try {
            UIManager.setLookAndFeel(Configuration.getInstance().getLookAndFeel());
        } catch (Exception e) {}
        
        initComponents();
        this.setTitle(title);
        progressBar.setMaximum(100);
        progressBar.setMinimum(0);
        progressBar.setStringPainted(true);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width - this.getWidth() - 10, screenSize.height - this.getHeight() -40 );
     }

    public Progress(java.awt.Frame parent, boolean modal, String title, boolean indeterminate) {
        super(parent);
        initComponents();
        this.setTitle(title);
        progressBar.setIndeterminate(indeterminate);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width - this.getWidth() - 10, screenSize.height - this.getHeight() -40 );
     }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    public void update(Observable o, Object arg) {
        int progress = Integer.parseInt(arg.toString());
        if(progress == -1){
              this.dispose();
        }
        progressBar.setValue(progress);
    }

}
